# Generated by Django 5.0.2 on 2024-02-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.subreddit'),
        ),
    ]
